logging:
  level:
    root: debug

server:
  port: 1234

spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
        registration:
          naver:
            client-id: V87zFuapy7EMvwR99qMT
            client-secret: BVWf3NfoRw
            client-name: naver
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            #redirect-uri: /api/user/oauth2/naver
          kakao:
            client-id: d53699f1b9a2e4e717750f837cfc5e9c
            client-secret: YBBLuJNLYDgn5ZGnZZ2mFWUdMMxuxQOG
            client-name: kakao
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            clientAuthenticationMethod : client_secret_post

            #redirect-uri: /api/user/oauth2/kakao
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto : none
